### ISSUE TITLE
[Request] Filter for Inventory Setups plugin

### ISSUE THREAD

**Issue by UnIockables** [salverrs/GE-Filters#1]
Cool plugin man, really useful!
If you plan on adding to this in the future, could there be a 4th filter that filters items from the Inventory Setups plugin, similar to how the Bank Tags option works?

**Comment by salverrs** [comment]
Thanks! Sorry for the slow response. 
I'll start working on adding Inventory Setups today and hopefully it should be in the plugin by the end of the week :)

**Comment by salverrs** [comment]
Inventory Setups support has been added!
