### ISSUE TITLE
Plugin Incompatible. Needs Updating.

### ISSUE THREAD

**Issue by felma4mnrla** [salverrs/GE-Filters#7]
Incompatible with current Runelite version.

**Comment by Bass-Music** [comment]
@salverrs bumping this update request. Love the plugin and hope it gets updated. Thanks!

**Comment by Defiect** [comment]
@salverrs bumping as well. One of the best QoL plugins there exists, please let us know if you intend on maintaining this plugin or if it should be forked

**Comment by kulcris** [comment]
Looks like there were recent changes.

**Comment by salverrs** [comment]
Sorry about the wait, I've submitted a PR so it should be back in Runelite soon.
