### ISSUE TITLE
Plugin Incompatible With Latest Runelite Version 

### ISSUE THREAD

**Issue by m26ss** [salverrs/GE-Filters#8]

**Comment by Nick2bad4u** [comment]
![image](https://github.com/user-attachments/assets/4cd53243-d682-4858-9684-8a939ca57fcc)

**Comment by salverrs** [comment]
Sorry about the wait, I've submitted a PR so it should be back in Runelite soon.

**Comment by Nick2bad4u** [comment]
> Sorry about the wait, I've submitted a PR so it should be back in Runelite soon.

Thanks! If you want to add me as a collab I could help you next time it borks with an update.

**Comment by salverrs** [comment]
> > Sorry about the wait, I've submitted a PR so it should be back in Runelite soon.
> 
> Thanks! If you want to add me as a collab I could help you next time it borks with an update.

Will do, thank you. Closing issue now as plugin is back in the game :)
